// core/ui-react/src/features/config/auth/AuthConfigTab.tsx
import {Box} from "@mui/material";
import {useWatch} from "react-hook-form";

import type {ConfigValues} from "../../../api/config/schema";
import {
    ChipsSetting,
    ConfigFieldset,
    NumberSetting,
    SecretInput,
    SelectSetting,
    SwitchSetting,
    TextSetting,
} from "../components";
import {AuthUsersSection} from "./AuthUsersSection";
import {
    AUTH_TYPE_OPTIONS,
    AUTH_TYPE_TOOLTIP,
    OIDC_TOOLTIP,
    RESTRICTIONS_TOOLTIP,
} from "./authSettings";

/**
 * `F-CONFIG-AUTH`: the Authorization configuration tab -- every field of
 * `config-fields-service.js:2011-2375`, in legacy's order and grouping, bound
 * to `C-CONFIG-FORM`'s whole-config form through the `C-CONFIG-FIELDS`
 * vocabulary.
 *
 * Legacy's `hideExpression`s become plain conditional rendering driven by
 * `useWatch`, exactly as `F-CONFIG-MAIN` does: the shell's form is created
 * with `shouldUnregister: false`, so hiding a row never clears the value
 * behind it and never lets its validation rules block a save.
 */
export function AuthConfigTab() {
    const authType = useWatch<ConfigValues>({name: "auth.authType"});
    const authHeader = useWatch<ConfigValues>({name: "auth.authHeader"});
    const oidcIssuerUri = useWatch<ConfigValues>({name: "auth.oidcIssuerUri"});

    // `config-fields-service.js:2047-2090`.
    const headerFieldsVisible = authType !== "NONE" && authType !== "OIDC";
    const ipRangesVisible = headerFieldsVisible && !isEmpty(authHeader);
    // `config-fields-service.js:2102`.
    const oidcVisible = authType === "OIDC";
    // `config-fields-service.js:2118-2166`: the explicit endpoint fields hide
    // once an issuer URI is set, because discovery makes them redundant.
    const explicitOidcEndpointsVisible = isEmpty(oidcIssuerUri);
    // `config-fields-service.js:2234`, `:2299`.
    const restrictionsAndUsersVisible = authType !== "NONE";

    return (
        <Box data-testid="config-auth">
            <ConfigFieldset label="Main">
                <SelectSetting
                    label="Auth type"
                    name="auth.authType"
                    options={AUTH_TYPE_OPTIONS}
                    tooltip={AUTH_TYPE_TOOLTIP}
                />
                {headerFieldsVisible ? (
                    <TextSetting
                        advanced
                        help="Name of header that provides the username in requests from secure sources."
                        label="Auth header"
                        name="auth.authHeader"
                    />
                ) : null}
                {ipRangesVisible ? (
                    <ChipsSetting
                        advanced
                        help='IP ranges from which the auth header will be accepted. Apply with return key. Use IPv4 or IPv6 ranges like "192.168.0.1-192.168.0.100", CIDRs like 192.168.0.0/24 or single IP addresses like "127.0.0.1".'
                        label="Secure IP ranges"
                        name="auth.authHeaderIpRanges"
                    />
                ) : null}
                {headerFieldsVisible ? (
                    <SwitchSetting
                        help="Remember users with cookie for 14 days."
                        label="Remember users"
                        name="auth.rememberUsers"
                    />
                ) : null}
                {headerFieldsVisible ? (
                    <NumberSetting
                        advanced
                        help="How long users are remembered."
                        label="Cookie expiry"
                        name="auth.rememberMeValidityDays"
                        unit="days"
                    />
                ) : null}
            </ConfigFieldset>

            {oidcVisible ? (
                <ConfigFieldset label="OpenID Connect" tooltip={OIDC_TOOLTIP}>
                    <TextSetting
                        help="OIDC issuer URI used for provider discovery, for example https://idp.example.com/realms/master. Requires restart."
                        label="Issuer URI"
                        name="auth.oidcIssuerUri"
                    />
                    {explicitOidcEndpointsVisible ? (
                        <>
                            <TextSetting
                                advanced
                                help="Manual provider authorization endpoint. Required only when issuer URI is empty. Requires restart."
                                label="Authorization URI"
                                name="auth.oidcAuthorizationUri"
                            />
                            <TextSetting
                                advanced
                                help="Manual provider token endpoint. Required only when issuer URI is empty. Requires restart."
                                label="Token URI"
                                name="auth.oidcTokenUri"
                            />
                            <TextSetting
                                advanced
                                help="Manual provider user info endpoint. Required only when issuer URI is empty. Requires restart."
                                label="User info URI"
                                name="auth.oidcUserInfoUri"
                            />
                            <TextSetting
                                advanced
                                help="Manual provider JWK set endpoint. Required only when issuer URI is empty. Requires restart."
                                label="JWK set URI"
                                name="auth.oidcJwkSetUri"
                            />
                        </>
                    ) : null}
                    <TextSetting
                        help="OIDC client ID. Requires restart."
                        label="Client ID"
                        name="auth.oidcClientId"
                        required
                    />
                    <SecretInput
                        help="OIDC client secret. Requires restart."
                        label="Client secret"
                        name="auth.oidcClientSecret"
                        required
                    />
                    <TextSetting
                        help="Claim used to match OIDC users to Hydra users, for example preferred_username, email or sub. Requires restart."
                        label="Username claim"
                        name="auth.oidcUsernameClaim"
                        required
                    />
                    <ChipsSetting
                        help="OIDC scopes. Must include openid. Apply with return key. Requires restart."
                        label="Scopes"
                        name="auth.oidcScopes"
                    />
                    <TextSetting
                        advanced
                        help="Redirect URI template. Register the resolved URL at the provider. The default is {baseUrl}/login/oauth2/code/{registrationId}. Requires restart."
                        label="Redirect URI"
                        name="auth.oidcRedirectUri"
                        required
                    />
                </ConfigFieldset>
            ) : null}

            {restrictionsAndUsersVisible ? (
                <ConfigFieldset
                    label="Restrictions"
                    tooltip={RESTRICTIONS_TOOLTIP}
                >
                    <SwitchSetting
                        help="Restrict access to searching."
                        label="Restrict searching"
                        name="auth.restrictSearch"
                    />
                    <SwitchSetting
                        help="Restrict access to stats."
                        label="Restrict stats"
                        name="auth.restrictStats"
                    />
                    <SwitchSetting
                        help="Restrict access to admin functions."
                        label="Restrict admin"
                        name="auth.restrictAdmin"
                    />
                    <SwitchSetting
                        help="Restrict NZB details, comments and download links."
                        label="Restrict NZB details & DL"
                        name="auth.restrictDetailsDl"
                    />
                    <SwitchSetting
                        help="Restrict visibility of indexer selection box in search. Affects only GUI."
                        label="Restrict indexer selection box"
                        name="auth.restrictIndexerSelection"
                    />
                    <SwitchSetting
                        help="Allow access to stats via external API."
                        label="Allow stats access"
                        name="auth.allowApiStats"
                    />
                </ConfigFieldset>
            ) : null}

            {restrictionsAndUsersVisible ? (
                <ConfigFieldset label="Users">
                    <AuthUsersSection />
                </ConfigFieldset>
            ) : null}
        </Box>
    );
}

function isEmpty(value: unknown): boolean {
    return value === null || value === undefined || value === "";
}

// core/ui-src/hydra-ng/src/app/components/config/tabs/auth-config-tab/auth-config-tab.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from "@angular/core";
import {FormGroup} from "@angular/forms";
import {FormlyFieldConfig, FormlyFormOptions} from "@ngx-formly/core";
import {ConfigService} from "../../../../services/config.service";

@Component({
    selector: "app-auth-config-tab",
    templateUrl: "./auth-config-tab.component.html",
    standalone: false
})
export class AuthConfigTabComponent implements OnInit {
    @Input() showAdvanced = false;
    @Output() dirtyChange = new EventEmitter<boolean>();
    @Output() validChange = new EventEmitter<boolean>();

    form = new FormGroup({});
    model: any = {
        authType: "NONE",
        authHeader: "",
        authHeaderIpRanges: [],
        rememberUsers: false,
        rememberMeValidityDays: 14,
        restrictSearch: true,
        restrictStats: true,
        restrictAdmin: true,
        restrictDetailsDl: true,
        restrictIndexerSelection: true,
        allowApiStats: false,
        users: []
    };
    options: FormlyFormOptions = {};
    fields: FormlyFieldConfig[] = [];

    constructor(private configService: ConfigService) {
    }

    ngOnInit() {
        this.loadConfig();
        this.setupForm();
    }

    private loadConfig() {
        this.configService.getConfig().subscribe({
            next: (config) => {
                this.model = config.auth;
                this.setupForm();
            },
            error: (error) => {
                console.error("Error loading config:", error);
            }
        });
    }

    private setupForm() {
        this.fields = [
            {
                wrappers: ["fieldset"],
                props: {
                    label: "Main"
                },
                fieldGroup: [
                    {
                        key: "authType",
                        type: "select",
                        props: {
                            label: "Auth type",
                            options: [
                                {label: "None", value: "NONE"},
                                {label: "HTTP Basic auth", value: "BASIC"},
                                {label: "Login form", value: "FORM"}
                            ],
                            description: "With auth type 'None' all areas are unrestricted. With auth type 'Form' the basic page is loaded and login is done via a form. With auth type 'Basic' you login via basic HTTP authentication. With all areas restricted this is the most secure as nearly no data is loaded from the server before you auth. Logging out is not supported with basic auth."
                        }
                    },
                    {
                        key: "authHeader",
                        type: "input",
                        props: {
                            label: "Auth header",
                            type: "text",
                            description: "Name of header that provides the username in requests from secure sources.",
                            advanced: true
                        },
                        expressions: {
                            hide: "model.authType === 'NONE'"
                        }
                    },
                    {
                        key: "authHeaderIpRanges",
                        type: "chipsInput",
                        props: {
                            label: "Secure IP ranges",
                            placeholder: "Enter IP ranges...",
                            description: "IP ranges from which the auth header will be accepted. Use IPv4 or IPv6 ranges like '192.168.0.1-192.168.0.100', CIDRs like 192.168.0.0/24 or single IP addresses like '127.0.0.1'.",
                            advanced: true
                        },
                        expressions: {
                            hide: "model.authType === 'NONE' || !model.authHeader"
                        }
                    },
                    {
                        key: "rememberUsers",
                        type: "checkbox",
                        props: {
                            label: "Remember users",
                            description: "Remember users with cookie for 14 days."
                        },
                        expressions: {
                            hide: "model.authType === 'NONE'"
                        }
                    },
                    {
                        key: "rememberMeValidityDays",
                        type: "input",
                        props: {
                            label: "Cookie expiry",
                            type: "number",
                            description: "How long users are remembered.",
                            advanced: true
                        },
                        expressions: {
                            hide: "model.authType === 'NONE'"
                        }
                    }
                ]
            },
            {
                wrappers: ["fieldset"],
                props: {
                    label: "Restrictions",
                    description: "Select which areas/features can only be accessed by logged in users (i.e. are restricted). If you don't want to allow anonymous users to do anything just leave everything selected."
                },
                expressions: {
                    hide: "model.authType === 'NONE'"
                },
                fieldGroup: [
                    {
                        key: "restrictSearch",
                        type: "checkbox",
                        props: {
                            label: "Restrict searching",
                            description: "Restrict access to searching."
                        }
                    },
                    {
                        key: "restrictStats",
                        type: "checkbox",
                        props: {
                            label: "Restrict stats",
                            description: "Restrict access to stats."
                        }
                    },
                    {
                        key: "restrictAdmin",
                        type: "checkbox",
                        props: {
                            label: "Restrict admin",
                            description: "Restrict access to admin functions."
                        }
                    },
                    {
                        key: "restrictDetailsDl",
                        type: "checkbox",
                        props: {
                            label: "Restrict NZB details & DL",
                            description: "Restrict NZB details, comments and download links."
                        }
                    },
                    {
                        key: "restrictIndexerSelection",
                        type: "checkbox",
                        props: {
                            label: "Restrict indexer selection box",
                            description: "Restrict visibility of indexer selection box in search. Affects only GUI."
                        }
                    },
                    {
                        key: "allowApiStats",
                        type: "checkbox",
                        props: {
                            label: "Allow stats access",
                            description: "Allow access to stats via external API."
                        }
                    }
                ]
            },
            {
                type: "repeat",
                key: "users",
                props: {
                    label: "Users",
                    description: "Configure users for authentication"
                },
                expressions: {
                    hide: "model.authType === 'NONE'"
                },
                fieldArray: {
                    fieldGroup: [
                        {
                            key: "username",
                            type: "input",
                            props: {
                                label: "Username",
                                type: "text",
                                required: true
                            }
                        },
                        {
                            key: "password",
                            type: "input",
                            props: {
                                label: "Password",
                                type: "password",
                                required: true
                            }
                        },
                        {
                            key: "maySeeAdmin",
                            type: "checkbox",
                            props: {
                                label: "May see admin area"
                            }
                        },
                        {
                            key: "maySeeStats",
                            type: "checkbox",
                            props: {
                                label: "May see stats"
                            },
                            expressions: {
                                hide: "model.maySeeAdmin"
                            }
                        },
                        {
                            key: "maySeeDetailsDl",
                            type: "checkbox",
                            props: {
                                label: "May see NZB details & DL links"
                            },
                            expressions: {
                                hide: "model.maySeeAdmin"
                            }
                        },
                        {
                            key: "showIndexerSelection",
                            type: "checkbox",
                            props: {
                                label: "May see indexer selection box"
                            },
                            expressions: {
                                hide: "model.maySeeAdmin"
                            }
                        }
                    ]
                }
            }
        ];
    }

    // Method to get current model for saving
    getCurrentModel(): any {
        return this.model;
    }

    // Method to check if form is dirty
    isDirty(): boolean {
        return this.form.dirty;
    }

    // Method to check if form is valid
    isValid(): boolean {
        return this.form.valid;
    }

    // Method to mark form as pristine (after save)
    markAsPristine() {
        this.form.markAsPristine();
        this.dirtyChange.emit(false);
    }

    onSubmit() {
        if (this.form.valid) {
            console.log("Auth form submitted:", this.model);
        }
    }
} 
<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <formly-form [form]="form" [fields]="fields" [model]="model" [options]="options">
  </formly-form>
</form>
